//! Chrome icon table. Each constant is an SVG asset path (`icons/…`) served
//! by `gpui-kit-assets`' `AllAssets` bundle; `icon(glyph, size)` renders one
//! as a `gpui_component::Icon` (the same SVG pipeline that
//! `PopupMenuItem::icon` / `Button::icon` consume). SVGs paint with the
//! surrounding text color (set `.text_color(...)` on an ancestor).
//!
//! The table and the `ALL` walk list are generated by one macro, so the guard
//! test at the bottom structurally covers every constant: an upstream rename
//! fails a test instead of rendering blank.

use gpui::{Styled as _, px};

/// A chrome icon: the asset path (`icons/…`) of an SVG in the embedded
/// `gpui-kit-assets` bundle. The path is not validated at compile time —
/// the guard test is what pins every entry to the bundle.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct IconAsset(pub &'static str);

impl gpui_kit_assets::IconNamed for IconAsset {
    fn path(self) -> gpui::SharedString {
        self.0.into()
    }
}

macro_rules! icon_table {
    ($($name:ident => $path:literal,)*) => {
        $(pub const $name: IconAsset = IconAsset($path);)*
        /// Every chrome icon; the guard test's only input, generated from the
        /// same table as the constants so a new entry cannot skip it.
        pub const ALL: &[IconAsset] = &[$($name),*];
    };
}

icon_table! {
    ADD => "icons/plus.svg",
    ARCHIVE => "icons/archive.svg",
    ARCHIVE_RESTORE => "icons/archive-restore.svg",
    ARROW_LEFT => "icons/arrow-left.svg",
    ARROW_RIGHT => "icons/arrow-right.svg",
    CALENDAR => "icons/calendar.svg",
    CHEVRON_DOWN => "icons/chevron-down.svg",
    CHEVRON_RIGHT => "icons/chevron-right.svg",
    CLOSE => "icons/close.svg",
    CODE => "icons/code.svg",
    COMMENT_DISCUSSION => "icons/messages-square.svg",
    COPY => "icons/copy.svg",
    EXTENSIONS => "icons/puzzle.svg",
    FOLDER => "icons/folder.svg",
    FOLDER_OPENED => "icons/folder-open.svg",
    GLOBE => "icons/globe.svg",
    HOME => "icons/house.svg",
    LAYOUT_PANEL => "icons/panel-bottom.svg",
    LAYOUT_SIDEBAR_LEFT => "icons/panel-left.svg",
    LAYOUT_SIDEBAR_RIGHT => "icons/panel-right.svg",
    LINK_EXTERNAL => "icons/external-link.svg",
    MORE => "icons/ellipsis.svg",
    PIN => "icons/pin.svg",
    ROBOT => "icons/bot.svg",
    SEARCH => "icons/search.svg",
    SETTINGS_GEAR => "icons/settings.svg",
    SORT_PRECEDENCE => "icons/arrow-down-wide-narrow.svg",
    SYMBOL_FILE => "icons/file-text.svg",
    TAG => "icons/tag.svg",
    TERMINAL => "icons/terminal.svg",
    TOOLS => "icons/wrench.svg",
    TRASH => "icons/trash.svg",
    WAND => "icons/wand-sparkles.svg",
    WARNING => "icons/triangle-alert.svg",
}

/// Render one chrome icon at an explicit square size. Color inherits the
/// surrounding text color, like any text element.
pub fn icon(glyph: IconAsset, size: f32) -> gpui_component::Icon {
    gpui_component::Icon::default().path(glyph.0).size(px(size))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_constant_resolves_in_the_embedded_bundle() {
        // AllAssets embeds the full Lucide/GPUI Kit catalog; a miss here means
        // an upstream rename drifted the path and the icon would render blank
        // at runtime.
        for glyph in ALL {
            assert!(
                gpui_kit_assets::AllAssets::get(glyph.0).is_some(),
                "icon asset missing from the embedded bundle: {}",
                glyph.0
            );
        }
    }

    #[test]
    fn icon_paths_are_unique() {
        // A duplicated path means two names silently share one drawing.
        for (i, glyph) in ALL.iter().enumerate() {
            for other in &ALL[i + 1..] {
                assert_ne!(glyph.0, other.0, "{} and {} share a path", glyph.0, other.0);
            }
        }
    }
}
